import { URL_API } from "./URL_API.";

const URL_CONTROLLERS = {
  USUARIO: URL_API + "/usuarios",
  PROJETO: URL_API + "/projeto",
  MOCK_MATERIAIS: URL_API + "/mock-materials",
  CIDADE: URL_API + "/cidades",
  ESTADO: URL_API + "/estados",
  ZONEAMENTO_BIOCLIMATICO: URL_API + "/zoneamento-bioclimatico",
  MATERIAL_PROJETO: URL_API + "/materialProjeto",
  CALCULO_TERMICO: URL_API + "/calculo-termico"
}

const  URL_ENDPOINTS = {
  LOGIN: URL_CONTROLLERS.USUARIO + "/login",
  MOCK_MATERIAIS: {
    GET_CATEGORIAS: URL_CONTROLLERS.MOCK_MATERIAIS + "/materialCategorias",
    GET_ALL_MATERIALS: URL_CONTROLLERS.MOCK_MATERIAIS,
    FILTRAR_MATERIAIS: URL_CONTROLLERS.MOCK_MATERIAIS,
    GET_MATERIAL_BY_ID: URL_CONTROLLERS.MOCK_MATERIAIS + "/getMaterialById/",
    GET_MATERIALS_BY_CATEGORY: URL_CONTROLLERS.MOCK_MATERIAIS + "/getMaterialsByCategory/",
    GET_MATERIALS_BY_TIPO_PRODUTO: URL_CONTROLLERS.MOCK_MATERIAIS + "/getMaterialsBytipoProduto/",
    GET_MATERIALS_BY_TIPO_FAMILIA: URL_CONTROLLERS.MOCK_MATERIAIS + "/getMaterialsByTipoFamilia/"
  },
  PROJETO: {
    GET_PROJETOS_BY_USUARIO: URL_CONTROLLERS.PROJETO + "/getProjetoByUsuario/",
    GET_PROJETO_BY_ID: URL_CONTROLLERS.PROJETO + "/", 
    CRIAR_PROJETO: URL_CONTROLLERS.PROJETO,
    ATUALIZAR_PROJETO: URL_CONTROLLERS.PROJETO + "/atualizarProjeto/",
    DELETAR_PROJETO: URL_CONTROLLERS.PROJETO + "/deletarProjeto/"
  },
  USUARIO:{
    CRIAR_USUARIO: URL_CONTROLLERS.USUARIO,
    BUSCAR_POR_ID: URL_CONTROLLERS.USUARIO + "/",
    ATUALIZAR_USUARIO: URL_CONTROLLERS.USUARIO + "/",
    DELETAR_USUARIO: URL_CONTROLLERS.USUARIO + "/"
  },
  CIDADE:{
    CRIAR_CIDADE: URL_CONTROLLERS.CIDADE,
    CRIAR_CIDADE_USUARIO: URL_CONTROLLERS.CIDADE + "/usuario/:usuarioId",
    LISTAR_TODOS: URL_CONTROLLERS.CIDADE,
    BUSCAR_POR_ID: URL_CONTROLLERS.CIDADE + "/",
    BUSCAR_POR_UF: URL_CONTROLLERS.CIDADE + "/uf/",
    BUSCAR_POR_NOME_E_UF: URL_CONTROLLERS.CIDADE + "/buscar",
    BUSCAR_POR_NOME: URL_CONTROLLERS.CIDADE + "/buscar-nome/",
    BUSCAR_POR_UF_E_NOME: URL_CONTROLLERS.CIDADE + "/buscar-uf-nome/",
    ATUALIZAR_CIDADE: URL_CONTROLLERS.CIDADE + "/",
    DELETAR_CIDADE: URL_CONTROLLERS.CIDADE + "/",
    EXISTE_POR_NOME_E_UF: URL_CONTROLLERS.CIDADE + "/existe/",
  },
  ESTADO:{
    CRIAR_ESTADO: URL_CONTROLLERS.ESTADO,
    LISTAR_TODOS: URL_CONTROLLERS.ESTADO,
    BUSCAR_POR_ID: URL_CONTROLLERS.ESTADO + "/",
    BUSCAR_POR_UF: URL_CONTROLLERS.ESTADO + "/uf/",
    BUSCAR_POR_NOME: URL_CONTROLLERS.ESTADO + "/buscar",
    ATUALIZAR_ESTADO: URL_CONTROLLERS.ESTADO + "/",
    DELETAR_ESTADO: URL_CONTROLLERS.ESTADO + "/",
    EXISTE_POR_UF: URL_CONTROLLERS.ESTADO + "/existe-uf/",
  },
  ZONEAMENTO_BIOCLIMATICO:{
    CRIAR_ZONEAMENTO: URL_CONTROLLERS.ZONEAMENTO_BIOCLIMATICO,
    LISTAR_TODOS: URL_CONTROLLERS.ZONEAMENTO_BIOCLIMATICO,
    BUSCAR_POR_ID: URL_CONTROLLERS.ZONEAMENTO_BIOCLIMATICO + "/",
    BUSCAR_POR_UF: URL_CONTROLLERS.ZONEAMENTO_BIOCLIMATICO + "/uf/",
    BUSCAR_POR_CIDADE: URL_CONTROLLERS.ZONEAMENTO_BIOCLIMATICO + "/cidade",
    BUSCAR_POR_ZONA_BIOCLIMATICA: URL_CONTROLLERS.ZONEAMENTO_BIOCLIMATICO + "/zona/",
    BUSCAR_POR_NOME_CIDADE: URL_CONTROLLERS.ZONEAMENTO_BIOCLIMATICO + "/buscar-cidade/",
    BUSCAR_POR_CIDADE_ID: URL_CONTROLLERS.ZONEAMENTO_BIOCLIMATICO + "/cidade-id/",
    ATUALIZAR_ZONEAMENTO: URL_CONTROLLERS.ZONEAMENTO_BIOCLIMATICO + "/",
    DELETAR_ZONEAMENTO: URL_CONTROLLERS.ZONEAMENTO_BIOCLIMATICO + "/",
  },
  MATERIAL_PROJETO:{
    BUSCAR_MATERIAIS_COM_PROPRIEDADES_TERMICAS: URL_CONTROLLERS.MATERIAL_PROJETO + "/propriedades-termicas/projeto/",
    ADICIONAR_MATERIAL_DO_CATALOGO: URL_CONTROLLERS.MATERIAL_PROJETO + "/propriedades-termicas/do-catalogo/",
    ADICIONAR_MATERIAL_CUSTOMIZADO: URL_CONTROLLERS.MATERIAL_PROJETO + "/propriedades-termicas/customizado/",
    ATUALIZAR_PROPRIEDADES_TERMICAS: URL_CONTROLLERS.MATERIAL_PROJETO + "/propriedades-termicas/",
    REMOVER_MATERIAL_DO_PROJETO: URL_CONTROLLERS.MATERIAL_PROJETO + "/propriedades-termicas/"
  },
  CALCULO_TERMICO:{
    CALCULAR_PROPRIEDADES_TERMICAS: URL_CONTROLLERS.CALCULO_TERMICO + "/calcular",
    CALCULAR_CARBONO_IMCORPORADO: URL_CONTROLLERS.CALCULO_TERMICO + "/carbono/"
  }
}
 

export  default URL_ENDPOINTS; 